// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rceryroeczzetpbhmnaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZXJ5cm9lY3p6ZXRwYmhtbmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTY3NDksImV4cCI6MjA2MDk5Mjc0OX0.qNluc2P0UCUK3a3hhqkzuYui_a_vZtBwf4FZIweY1Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);